title: CJ Chin
description: >- # this means the following lines will be treated as a single string
  Welcome to my Data Science Portfolio — showcasing projects, visualizations, and skills.
theme: jekyll-theme-minimal
logo: /assets/img/profile.png  # optional
show_downloads: false
google_analytics: # Add your tracking ID if needed

